if(PKG_USER-NEP)
  set(USER-NEP_SOURCES
    ${LAMMPS_SOURCE_DIR}/USER-NEP/pair_NEP.cpp
    ${LAMMPS_SOURCE_DIR}/USER-NEP/nep.cpp
  )

  set(USER-NEP_HEADERS
    ${LAMMPS_SOURCE_DIR}/USER-NEP/pair_NEP.h
    ${LAMMPS_SOURCE_DIR}/USER-NEP/nep.h
    ${LAMMPS_SOURCE_DIR}/USER-NEP/dftd3para.h
  )

  get_property(LAMMPS_HEADERS GLOBAL PROPERTY HEADERS)
  list(APPEND LAMMPS_HEADERS ${USER-NEP_HEADERS})
  set_property(GLOBAL PROPERTY HEADERS "${LAMMPS_HEADERS}")

  get_target_property(LAMMPS_SOURCES lammps SOURCES)
  list(APPEND LAMMPS_SOURCES ${USER-NEP_SOURCES})
  set_property(TARGET lammps PROPERTY SOURCES "${LAMMPS_SOURCES}")
endif()

